version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    networks:
      - testnet

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - testnet

  test-runner:
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: test
    networks:
      - testnet
    command: mvn test

networks:
  testnet:
