spring:
  application:
    name: task-manager-test

  datasource:
    url: jdbc:postgresql://postgres:5432/testdb
    username: testuser
    password: testpass

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 600000  # 10 minutes

  data:
    redis:
      host: redis
      port: 6379

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

jwt:
  secret-key: mYiADZOy9Hq5pTfomhj9hPUJLGAN/ZB6AZ4yoHfCtN0f8DaNQr6+4qeaJ9YfMK4ZbX85J3ao6TotW+jrLKLGeafpaYYLn2mmrYOB/1mJzhQYEaf883PtWAIwnTwHpPuEsJAhyHwEtlTvy++pZA+0bns66RUDBk80bJUA4JhJUI8
  access-expiration-time: 3600000
  refresh-expiration-time: 604800000

logging:
  level:
    org.springframework.cache: DEBUG
